# Build stage
FROM node:slim as build

# Create app directory
WORKDIR /opt/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app source
COPY . .

# Creates a "dist" folder with the production build
RUN npm run build:review-processor

# Run tests
RUN npm run test:review-processor

# Runtime stage
FROM node:slim as runtime

# Create app directory
WORKDIR /opt/app

COPY .env.development.docker ./.env.development.docker
COPY --from=build /opt/app/dist ./dist
COPY --from=build /opt/app/package*.json ./

# Install app dependencies
RUN npm install --omit=dev

# Start the server using the production build
CMD ["npm", "run", "start:prod:review-processor"]
