FROM node:slim

# Create app directory
WORKDIR /opt/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Copy docker config
COPY .env.development.docker .env.development.docker

# Creates a "dist" folder with the production build
RUN npm run build

# Start the server using the production build
CMD ["npm", "run", "start:prod:review-processor"]
